Bookers/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root :to => 'books#new'
  get 'books' => 'books#index'
  post 'books' => 'books#create', as: 'create_book'
  get 'books/:id' => 'books#show', as: 'detail_book'
  get 'books/:id/edit' => 'books#edit', as: 'edits_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully created."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "Book was successfully updated."
    else
     render "edit"
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to create_book_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :category, :body)
  end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/books_helper.rb
module BooksHelper
end

Bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_with model:@book, url:"/books/#{@book.id}", local:true do |f| %>
 <% if @book.errors.any? %>
<h3><%= pluralize(@book.errors.count,"error") %> prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
  <ul>
      <li><%= message %></li>
  </ul>
    <% end %>
 <% end %>
 <h4> title </h4>
 <%= f.text_field :title %>
 <h4> body </h4>
 <%= f.text_area :body %>
 <div><%= f.submit 'Update Book' %></div>
<% end %>

<p> <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", create_book_path %> </p>

Bookers/app/views/books/index.html.erb
<h1>Books</h1>
<table>
   <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
    <% @books.each do |book| %>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "Show", book_path(book.id) %></td>
     <td><%= link_to "Edit", edits_book_path(book.id) %></td>
     <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
    </tr>
    <% end %>
       </thead>
  </table>

<h2> New book </h2>

<!-- form_with部分 -->
<%= form_with model: @book, local: true do |f| %>
  <% if @book.errors.any? %>
  <h3><%= pluralize(@book.errors.count,"error") %> prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
  <ul>
      <li><%= message %></li>
  </ul>
  <% end %>
  <% end %>
 <div>
    <label for="book_title">Title</label>
    <%= f.text_field :title %>
  </div>

  <div>
    <label for="book_body">Body</label>
    <%= f.text_area :body %>

  <div>
  <%= f.submit 'Create Book' %>
  </div>

<% end %>

Bookers/app/views/books/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebCampBackendNew</title>
  </head>

  <body>
    <h1>
      ようこそ
      <strong>Bookers</strong>
      へ！
    </h1>

    <p>
      <strong>Bookers</strong>
      では、さまざまな書籍に関するあなたの意見や
    </p>
    <p>印象を共有し交換することができます</p>

    <p>
      <a href="/books">start</a>
    </p>
  </body>
</html>

Bookers/app/views/books/show.html.erb
<% if flash[:notice] %>
<%=flash[:notice] %>
<% end %>

<p> <strong> Title: </strong> <%= @book.title %> </p>

<p> <strong> Body: </strong> <%= @book.body %> </p>

<p> <%= link_to "Edit", edits_book_path(@book.id) %> | <%= link_to "Back", create_book_path %> </p>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>